config/routes.rb
Spree::Core::Engine.routes.draw do

  resources :contacts, controller: 'contact_us/contacts'
  get '/contact-us' => 'contact_us/contacts#index', :as => :contact_us
end

app/models/spree/contact_us/contact.rb
module Spree
  module ContactUs
    class Contact

      include ActiveModel::Conversion
      include ActiveModel::Validations

      attr_accessor :email, :message, :name, :subject, :phone, :reasons

      EMAIL_REGEX = /\A
        [^\s@]+ # non-at-sign characters, at least one
          @     # at-sign
        [^\s.@] # non-at-sign and non-period character
        [^\s@]* # 0 or more non-at-sign characters, accepts any number of periods
         \.     # period
        [^\s@]* # 0 or more non-at-sign characters, accepts any number of periods
        [^\s.@] # non-at-sign and non-period character
      \z/x

      validates :email,   :format => { :with => EMAIL_REGEX },
                          :presence => true
      validates :message, :presence => true
      validates :phone, :presence => true
      validates :reasons, :presence => true
      validates :name,    :presence => {:if => Proc.new{SpreeContactUs.require_name}}
      validates :subject, :presence => {:if => Proc.new{SpreeContactUs.require_subject}}


      def initialize(attributes = {})
        [:email, :message, :name, :subject, :phone, :reasons].each do |attribute|
          self.send("#{attribute}=", attributes[attribute]) if attributes and attributes.has_key?(attribute)
        end
      end

      def save
        if self.valid?
          Spree::ContactUs::ContactMailer.contact_email(self).deliver
          return true
        end
        return false
      end

      def persisted?
        false
      end

    end
  end
end

app/controllers/spree/contact_us/contacts_controller.rb
class Spree::ContactUs::ContactsController < Spree::StoreController

  helper "spree/products"
  def create
    @contact = Spree::ContactUs::Contact.new(params[:contact_us_contact])

    if @contact.save
      if Spree::ContactUs::Config.contact_tracking_message.present?
        flash[:contact_tracking] = Spree::ContactUs::Config.contact_tracking_message
      end
      # redirect_to(spree.contact_us_path, :notice => Spree.t('contact_us.notices.success'))
      redirect_to(:back, :notice => Spree.t('contact_us.notices.success'))
    else
      render :index
    end
  end

  def index
    @contact = Spree::ContactUs::Contact.new
    @taxonomies = Spree::Taxonomy.includes(root: :children)
  end

  private

  def accurate_title
    Spree.t(:contact_us_title)
  end

end

app/views/spree/contact_us/contacts/index.html.erb
<% content_for :head do -%>
  <meta name="title" content="<%= Spree.t(:contact_us_title) %>">
<% end -%>

<% content_for :sidebar do
   if "products" == @current_controller && @taxon %>
    <%= render :partial => "spree/shared/filters" %>
  <% else %>
    <%= render :partial => "spree/shared/taxonomies" %>
  <% end
 end %>

<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @contact } %>

<h1><%= Spree.t(:contact_us_title) %></h1>
<%= form_for @contact, :url => contacts_path, :html => { :novalidate => '' } do |f| %>
  <% if SpreeContactUs.require_name %>
    <p>
      <%= f.label :name %>
      <span class="required">*</span><br/>
      <%= f.text_field :name, class: 'required form-control' %>
    </p>
  <% end %>
  <p>
    <%= f.label :email %>
    <span class="required">*</span><br/>
    <%= f.email_field :email, class: 'required form-control email' %>
  </p>
  <% if SpreeContactUs.require_subject %>
    <p>
      <%= f.label :subject %>
      <span class="required">*</span><br/>
      <%= f.text_field :subject, class: 'required form-control' %>
    </p>
  <% end %>
  <p>
    <%= f.label :message %>
    <span class="required">*</span><br/>
    <%= f.text_area :message, class: 'required form-control' %>
  </p>
  <p>
    <%= f.submit Spree.t(:submit), :alt => Spree.t(:submit), :id => 'contact_us_contact_submit', :title => Spree.t(:submit), :class => 'btn btn-primary' %>
  </p>
<% end %>